Treat emote set ids properly (as strings)
robotty/twitch-irc-rs pull request #162
Opened 2022-05-07 07:38 UTC by FoxLisk

Emote set ids are strings - the docs say so (see https://dev.twitch.tv/docs/api/reference#get-emote-sets) and also empirically I see uuid-looking strings constantly. I get a bunch of error messages like

```
Error: Failed to parse incoming message as ServerMessage (emitting as generic instead): Could not parse IRC message @badge-info =;badges=moderator/1;color=#8A2BE2;display-name=Bot_Lisk;emote-sets=0,75c09c7b-332a-43ec-8be8-1d4571706155;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #foxlisk as ServerMessage: Malformed tag value for tag `emote-sets`, value was `0,75c09c7b-332a-43ec-8be8-1d4571706155`
```

That is in fact a valid emote set id; it turns out that it is the set of follower emotes, so I'm guessing that follower emotes were the first ones to break the convention of using integers for emote sets.

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

2022-05-11 14:08 UTC, RAnders00 requested changes

2022-05-11 14:08 UTC, RAnders00 commented on src/message/commands/globaluserstate.rs
> +                emote_sets: HashSet::from_iter(vec!["0".to_string()]),
```suggestion
                emote_sets: HashSet::from_iter(vec!["0".to_owned()]),
```

2022-05-11 14:08 UTC, RAnders00 commented on CHANGELOG.md
> +- Breaking: Handle `emote_sets` as `String`s since not all of them are in fact `u64`s
```suggestion
- Breaking: Handle `emote_sets` as `String`s since not all of them are in fact `u64`s (#162)
```

2022-05-11 14:10 UTC, RAnders00 commented
Thank you for this PR! I wasn‘t aware of this problem, and I really appreciate you taking the time to make the changes!

2022-05-13 00:53 UTC, FoxLisk commented
Feedback resolved (I hope!) - glad to help with this very useful library :)

2022-05-15 10:33 UTC, RAnders00 submitted a review, later dismissed

2022-05-15 10:33 UTC, RAnders00 approved these changes

2022-05-15 10:38 UTC, merged

2022-05-15 10:43 UTC, RAnders00 commented
Thank you!